// frontend/src/components/Login.vue
`
`,

<template>
  <div>
    <h1>Login</h1>
    <form v-on:submit.prevent>
      <label>
        Username
        <input v-model='username' type='text'/>
      </label>
      <label>
        Password
        <input v-model='password' type='password'/>
      </label>
      <button class='btn btn-primary' v-on:click='login'>
        Login
      </button>
    </form>
  </div>
</template>

<script>
  import Services from './services'
  import {session as credentials} from '../session'

  export default {
    data () {
      return {
        username: '',
        password: ''
      }
    },
    methods: {
      login () {
        Services.login(this.username, this.password)
          .then((json) => {
            this.$router.push('')
            credentials.loggedIn = true
            credentials.username = json.username
            credentials.id = json.id
          })
          .catch((err) => {
            console.warn(err)
          })
      }
    }
  }

</script>

<!-- Add 'scoped' attribute to limit CSS to this component only -->
<style scoped>
</style>

// frontend/src/pages/Login.tsx
import React, {useState} from "react";
import {Api} from "../services/Api";

const Login: React.FC<any> = ({handleSuccessfulLogin}) => {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    function handleLogin (evt: React.MouseEvent) {
        evt.preventDefault()
        Api.login(username, password)
            .then((userDetails) => {
                handleSuccessfulLogin(userDetails)
            }).catch((err) => {
                //TODO: Handle error message somewhere
                console.warn(err)
        })
    }

    return (
        <div>
            <h1>Login</h1>
            <form>
                <label>
                    Username
                    <input type='text' value={username} onChange={(evt) => setUsername(evt.target.value)}/>
                </label>
                <label>
                    Password
                    <input type='password' value={password} onChange={(evt) => setPassword(evt.target.value)}/>
                </label>
                <button className='btn btn-primary' onClick={handleLogin}>
                    Login
                </button>
            </form>
        </div>
    );
}

export default Login;
