// frontend/src/components/Workouts.vue
<template>
  <div>
    <div class='row'>
      <div class='col'>
        <h1>Workouts</h1>
      </div>
    </div>
    <div class='row'>
      <div class='col'>
        <div class='card'>
          <div class='card-header'>
            Add Workout
          </div>
          <div class='card-body'>
            <div class='row'>
              <div class='col'>
                <label>Title: <input v-model='newWorkout.title' type='text'/></label>
              </div>
              <div class='col'>
                <label>Date: <input v-model='newWorkout.date' type='date'/></label>
              </div>
            </div>
            <div class='row'>
              <div class='col'>
                <label>Description: <textarea v-model='newWorkout.description'> </textarea></label>
              </div>
            </div>
            <div class='row'>
              <div class='col'>
                <button class='btn btn-primary' v-on:click='addWorkout'> Add Workout </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='row'>
      <h2>All Workouts</h2>
    </div>
    <div class='row'>
      <div class='col'>
        <table class='table'>
          <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Description</th>
          </tr>
          <tr v-for='workout in workouts'>
            <td>
              {{workout.date}}
            </td>
            <td>
              {{workout.title}}
            </td>
            <td>
              {{workout.description}}
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

</template>

<script>
  import Services from './services'
  import {session as credentials} from '../session'

  export default {
    name: 'bootstrap',
    data () {
      return {
        workouts: [],
        newWorkout: {},
        credentials: credentials
      }
    },
    methods: {
      getWorkouts () {
        Services.getWorkouts(credentials.id)
          .then(workouts => { this.workouts = workouts })
      },
      addWorkout () {
        Services.addWorkout(credentials.id, this.newWorkout.title, this.newWorkout.description, this.newWorkout.date)
          .then(json => {
            this.newWorkout = {}
            this.workouts.push(json)
          })
      }
    },
    created () {
      this.getWorkouts()
    }
  }

</script>

<style scoped>
</style>

// frontend/src/pages/Workouts.tsx
import React, {useEffect, useState} from "react";
import {Api, Workout} from "../services/Api";
import {Session} from "../Session";

export interface SessionProps {
    session: Session
}

const Workouts: React.FC<SessionProps> = ({session}) => {
    const [workouts, setWorkouts] = useState<Array<Workout>>([])

    useEffect(() => {
        const id = session.id
        if (id == null) {
            return
        }
        Api.getWorkouts(id)
            .then((workouts) => {
                setWorkouts(workouts);
            })
            .catch((err) => {
                console.warn(err)
            })


    }, [session.id])
    return (
        <div>
            <div className="row">
                <div className="col">
                    <h1>Workouts</h1>
                </div>
            </div>
            <div className="row">
                <div className="col">
                    <h2>All Workouts</h2>
                </div>
            </div>
            <div className="row">
                <div className="col">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Title</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                        {workouts.map((workout, index) => {
                            return (<tr key={index}>
                                <td>{workout.date}</td>
                                <td>{workout.title}</td>
                                <td>{workout.description}</td>
                            </tr>)
                        })}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}

export default Workouts;
