// frontend/src/App.tsx
import React, {useEffect, useState, Fragment} from 'react'
import {BrowserRouter as Router, Route, Switch, Redirect, Link} from 'react-router-dom'
import Index from "./pages/Index"
import Login from "./pages/Login"
import Workouts from "./pages/workouts/Workouts"

import './App.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import {Session} from "./Session"
import {Api} from "./services/Api"
import {LandingPage} from "./pages/LandingPage"
import {useInterval} from "./utils/hooks"


interface NavigationBarProps {
    session: Session,
    handleSuccessfulLogout(): void
}

const NavigationBar: React.FC<NavigationBarProps> = ({session, handleSuccessfulLogout}) => {
    function logout() {
        Api.logout()
            .then(() => handleSuccessfulLogout())
            .catch((err) => {
                //TODO: Handle
                console.warn(err)
            })
    }

    const signedIn = session.id !== null

    return (
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="container">
                <Link className="navbar-brand" to="/">Gym Buddy</Link>
                <ul className="navbar-nav ml-auto">
                    <li className="nav-item">{signedIn && (
                        <Link to="/workouts" className="nav-link">Workouts</Link>)}</li>
                    <li className="nav-item">{signedIn && (
                        <span onClick={logout} className="nav-link">Logout</span>)}</li>
                    <li className="nav-item">{!signedIn && (<Link to="/login" className="nav-link">Login</Link>)}</li>
                </ul>
            </div>
        </nav>
    )
}

interface PrivateRouteProps {
    session: Session
    children: React.ReactNode
}

const PrivateRoute: React.FC<PrivateRouteProps> = ({session, children}) => {
    return (
        <Fragment>
            {session.id != null ? children : <Redirect to='/login'/>}
        </Fragment>
    )

}

const App: React.FC = (props) => {
    const noSession: Session = {id: null, loaded: false}
    const [session, setSession] = useState<Session>(noSession)

    function handleSuccessfulLogin(session: Session): void {
        setSession({...session, loaded: true})
    }

    function handleSuccessfulLogout(): void {
        setSession({id: null, loaded: true})
    }

    useInterval(() => {
        if (session.loaded && session.id != null) {
            Api.logcheck()
                .then((json) => {
                })
                .catch((err) => {
                    // TODO: Don't log out, display modal
                    handleSuccessfulLogout()
                })
        }

    }, 30000)

    useEffect(() => {
        Api.logcheck()
            .then((json) => {
                handleSuccessfulLogin(json)
            })
            .catch((err) => {
                handleSuccessfulLogout()
            })
    }, [])
    return (
        <Router>
            {session.loaded &&
            (
                <div>
                    <NavigationBar session={session} handleSuccessfulLogout={handleSuccessfulLogout}/>
                    <div className="container">
                        <Switch>
                            <Route path="/" exact>
                                {session.id ?
                                    (<Index session={session}/>) : <LandingPage/>
                                }
                            </Route>
                            <Route path="/login/">
                                <Login session={session} handleSuccessfulLogin={handleSuccessfulLogin}/>
                            </Route>
                            <PrivateRoute session={session}>
                                <Route path="/" exact>
                                </Route>
                                <Route path="/workouts">
                                    <Workouts session={session}/>
                                </Route>
                            </PrivateRoute>
                        </Switch>
                    </div>
                </div>
            )
            }

        </Router>
    )
}

export default App

// frontend/src/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Gym Buddy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li v-if="credentials.loggedIn" class="nav-item">
              <router-link class="nav-link" to="workouts">Workouts</router-link>
            </li>
            <li v-if="!credentials.loggedIn" class="nav-item">
              <router-link class="nav-link" to="login">Login</router-link>
            </li>
            <li v-if="!credentials.loggedIn" class="nav-item">
              <router-link class="nav-link" to="register">Register</router-link>
            </li>
            <li v-if="credentials.loggedIn" class="nav-item" v-on:click="logout">
              <span class="nav-link">Log Out</span>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
  import services from './components/services'
  import {session as credentials} from './session'

  export default {
    name: 'app',

    data () {
      return {
        credentials: credentials
      }
    },
    methods: {
      logout () {
        services.logout()
          .then(res => {
            credentials.loggedIn = false
            credentials.username = null
            credentials.id = null
          })
      }
    },
    created () {
      services.logcheck()
        .then(json => {
          credentials.loggedIn = true
          credentials.id = json.id
          credentials.username = json.username
        })
    }
  }
</script>

<style>
</style>
